// الملف الرئيسي لتعريف إصدارات محركات البناء
plugins {
    // تحديد إصدار محرك بناء تطبيقات أندرويد
    id 'com.android.application' version '8.2.0' apply false
    id 'com.android.library' version '8.2.0' apply false
    
    // دعم لغة كوتلن
    id 'org.jetbrains.kotlin.android' version '1.9.0' apply false
    
    // محرك خدمات جوجل (الإصدار الذي طلبته 4.4.4)
    id 'com.google.gms.google-services' version '4.4.4' apply false
}
