pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

// اسم المشروع الظاهر في النظام
rootProject.name = "NoSpam Japan"
// تضمين مجلد التطبيق الرئيسي
include ':app'
